# Generated by Django 5.0.3 on 2024-05-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_rename_image_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitulo',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='destino',
        ),
    ]
